from enum import Enum

class CompetencyLevel(str, Enum):
    BEGINNER = "BEGINNER"
    INTERMEDIATE = "INTERMEDIATE"
    ADVANCED = "ADVANCED"

class PinDirection(str, Enum):
    INPUT = "INPUT"
    OUTPUT = "OUTPUT"
    BIDIRECTIONAL = "BIDIRECTIONAL"
    POWER = "POWER"
    GROUND = "GROUND"
    PASSIVE = "PASSIVE"

class ComponentCategory(str, Enum):
    MICROCONTROLLER = "MICROCONTROLLER"
    SENSOR = "SENSOR"
    PASSIVE_COMPONENT = "PASSIVE_COMPONENT"
    ACTIVE_COMPONENT = "ACTIVE_COMPONENT"
    CONNECTOR = "CONNECTOR"
    POWER_SOURCE = "POWER_SOURCE"
    GROUND_NODE = "GROUND_NODE"
    ROUTING = "ROUTING"

class ValidationStatus(str, Enum):
    PASS = "PASS"
    FAIL = "FAIL"
    UNVALIDATED = "UNVALIDATED"

class ValidationSeverity(str, Enum):
    ERROR = "ERROR"
    WARNING = "WARNING"
    INFO = "INFO"

class ObjectType(str, Enum):
    PHYSICAL = "PHYSICAL"
    CIRCUIT_PRIMITIVE = "CIRCUIT_PRIMITIVE"
    DIGITAL_PRIMITIVE = "DIGITAL_PRIMITIVE"
    RTL_OBJECT = "RTL_OBJECT"
    SEMICONDUCTOR_PRIMITIVE = "SEMICONDUCTOR_PRIMITIVE"
    VERIFICATION_OBJECT = "VERIFICATION_OBJECT"
    VISUALIZATION_PRIMITIVE = "VISUALIZATION_PRIMITIVE"
    PACKAGING_OBJECT = "PACKAGING_OBJECT"
