// AI Assistant: the generation as a visible process. The phase list is derived from the job's real
// events; every verdict in it (electrical, function, schematic, physical build) comes from the
// deterministic checks, never from the AI.
import { useEffect, useMemo, useRef, useState } from 'react';
import { api } from '../api';
import type { Studio } from '../store';
import type { JobInfo, ProviderInfo } from '../types';
import { jobHeadline, jobPhases, type PhaseState } from '../ui/jobPhases';
import { checkCards } from '../ui/checks';
import type { CheckTab } from './ChecksPanel';

const SUGGESTIONS = [
  'An automatic night light that turns on an LED in the dark, powered by a 9 V battery, no microcontroller',
  'A temperature alarm using an LM35, a comparator, a transistor and a buzzer',
  'Blink an LED about once per second with a 555 timer from a 9 V battery',
  'Control the speed of a small DC motor with PWM from a Raspberry Pi Pico',
];

const ICON: Record<PhaseState, string> = { done: '✓', active: '', pending: '○', failed: '✕', skipped: '–' };

export function AssistantPanel({ studio, onGenerated, onRunning, openView, openCheck }: {
  studio: Studio; onGenerated: () => void; onRunning: (r: boolean) => void;
  openView: (v: 'schematic' | 'physical') => void; openCheck: (t: CheckTab) => void;
}) {
  const [prompt, setPrompt] = useState('');
  const [providers, setProviders] = useState<ProviderInfo[]>([]);
  const [model, setModel] = useState('');
  const [job, setJob] = useState<JobInfo | null>(null);
  const timer = useRef<number | null>(null);
  useEffect(() => { api.providers().then(p => { setProviders(p); const g = p.find(x => x.name === 'gemini'); if (g) setModel(g.default_model); }).catch(() => {}); }, []);
  useEffect(() => () => { if (timer.current) window.clearTimeout(timer.current); }, []);

  const configured = providers.some(p => p.configured);
  const running = job?.status === 'running';
  useEffect(() => { onRunning(!!running); }, [running, onRunning]);
  const phases = useMemo(() => jobPhases(job), [job]);
  const result = job?.status === 'done' ? job.result : undefined;
  const cards = useMemo(() => (result ? checkCards(result) : []), [result]);

  const poll = (id: string) => {
    api.job(id).then(info => {
      setJob(info);
      if (info.status === 'running') timer.current = window.setTimeout(() => poll(id), 900);
      else if (info.status === 'done' && info.result) {
        const r = info.result;
        void studio.load(async () => r, `Generated by ${info.model ?? 'AI'} and validated`).then(onGenerated);
      }
    }).catch(e => setJob(j => j ? { ...j, status: 'failed', error: String(e.message ?? e) } : j));
  };

  const start = async () => {
    const text = prompt.trim();
    if (!text || running) return;
    try {
      const provider = providers.find(p => p.configured)?.name ?? 'gemini';
      const { job_id } = await api.generate(text, provider, model || undefined);
      setJob({ job_id, status: 'running', prompt: text, events: [], trace_summary: {}, elapsed_s: 0 });
      poll(job_id);
    } catch (e) {
      setJob({ job_id: '', status: 'failed', prompt: text, events: [], trace_summary: {}, elapsed_s: 0, error: String((e as Error).message) });
    }
  };

  return (
    <div className="assistant">
      <div className="assist-scroll">
        {!job && (
          <div className="assist-intro">
            <h3>What do you want to build?</h3>
            <p className="muted">Describe the behaviour in plain language. The AI plans it from the component library;
              deterministic checks decide whether it is accepted, then the schematic and the breadboard build are generated.</p>
            <div className="roles"><span className="role ai">AI proposes</span><span className="role engine">Deterministic checks decide</span></div>
            <div className="suggest">
              {SUGGESTIONS.map(s => <button key={s} className="sugg" onClick={() => setPrompt(s)}>{s}</button>)}
            </div>
          </div>
        )}
        {job && (
          <div className="job">
            <div className="you-said"><span className="muted small">You asked</span><p>{job.prompt}</p></div>
            <div className={`jobstatus ${job.status}`}>{jobHeadline(job)}{job.model ? <span className="muted small"> · {job.model}</span> : null}</div>
            <ol className="phases">
              {phases.map(p => (
                <li key={p.id} className={`phase ${p.state}`}>
                  <span className="ph-ico">{p.state === 'active' ? <span className="spinner" /> : ICON[p.state]}</span>
                  <span className="ph-body">
                    <span className="ph-label">{p.label}<span className={`who ${p.who}`}>{p.who === 'ai' ? 'AI' : 'engine'}</span></span>
                    {p.detail && <span className="ph-detail">{p.detail}</span>}
                  </span>
                </li>
              ))}
            </ol>
            {job.error && <div className="err-msg">{job.error}</div>}
            {job.clarification && (
              <div className="note"><b>The AI needs a decision:</b> {job.clarification.reason}
                {job.clarification.missing_choices?.length ? <ul className="bul">{job.clarification.missing_choices.map((c, i) => <li key={i}>{c}</li>)}</ul> : null}
                <div className="muted">Add the missing detail to the request and generate again.</div></div>
            )}
            {result && (
              <div className="result-card">
                <div className="rc-title">{result.document.design.name}</div>
                <div className="rc-cards">
                  {cards.map(c => (
                    <button key={c.id} className={`rc-verdict ${c.tone}`} onClick={() => openCheck(c.id)}>
                      <span className="rc-k">{c.title}</span><span className="rc-v">{c.verdict}</span>
                    </button>
                  ))}
                </div>
                <div className="actions">
                  <button onClick={() => openView('schematic')}>View schematic</button>
                  <button onClick={() => openView('physical')} disabled={!result.physical?.applicable}>View breadboard in 3D</button>
                </div>
                {job.trace_summary && (
                  <div className="muted small">{String(job.trace_summary.model_call_count ?? '?')} model calls · {String(job.trace_summary.tool_call_count ?? '?')} tool calls · {String(job.trace_summary.repair_count ?? 0)} repairs · {Math.round(job.elapsed_s)} s</div>
                )}
              </div>
            )}
            {job.events.length > 0 && (
              <details className="raw-log">
                <summary>Activity log ({job.events.length})</summary>
                <div className="log">
                  {job.events.map((e, i) => <div key={i} className={e.message.includes('FAIL') ? 'fail' : e.message.includes('PASS') || e.event === 'COMPLETED' ? 'pass' : ''}>
                    <span className="t">{e.t.toFixed(0)}s</span>{e.message}</div>)}
                </div>
              </details>
            )}
            {!running && <button className="link" onClick={() => setJob(null)}>Start a new request</button>}
          </div>
        )}
      </div>
      <div className="composer">
        <textarea value={prompt} rows={3} placeholder="Describe a circuit, e.g. sound a buzzer when motion is detected, using an ESP32…"
                  onChange={e => setPrompt(e.target.value)} onKeyDown={e => { if (e.key === 'Enter' && (e.ctrlKey || e.metaKey)) void start(); }} />
        <div className="row">
          <select value={model} onChange={e => setModel(e.target.value)} title="Model">
            {['gemini-3.6-flash', 'gemini-3-flash-preview', 'gemini-3.5-flash', 'gemini-3.1-pro-preview'].map(m => <option key={m} value={m}>{m}</option>)}
          </select>
          <button className="primary" disabled={!prompt.trim() || running || !configured} onClick={() => void start()} title="Ctrl+Enter">
            {running ? 'Designing…' : 'Generate ↵'}
          </button>
        </div>
        {!configured && providers.length > 0 && <div className="err-msg small">No AI provider key on the server (set GEMINI_API_KEY and restart). Examples, library and editing work offline.</div>}
      </div>
    </div>
  );
}
